feat: add config option to switch modes with horizontal menu
tomosterlund/qalendar pull request #173
Opened 2023-06-03 15:27 UTC by wagnercateb

## Checklist

Please put "X" in the below checkboxes that apply::

- [ ] If committing a bugfix, I have tested it in different browsers (Chrome, Firefox, Safari). 
- [ ] If committing a new feature, I have first submitted an issue (Please note: you are free to open PRs for non-issued features, but opening an issue increases your chance of a successful PR). 
- [ ] If committing a new feature, I have also written an appropriate test suite for it. 
- [x ] New feature, non-issued features, no test suite

I have tested the following:  

- [x ] Qalendar component in month mode. 
- [ x] Qalendar component in week mode. 
- [ x] Qalendar component in day mode. 
- [ ] All of the above modes on emulated mobile view. (Oh no, not working correctly!)
- [ ] Dragging and dropping events. 
- [ ] Resizing events in day/week modes. (resizing windows the week option disappears when width < 744px)
- [ ] Clicking events to open event dialog. 

## This PR solves the following problem**. 

I have to click twice and navigate the modes menu to switch day/week/month. With a new config property I can set the menu horizontally so that I only need to click once.

## How to test this PR**. 

For example:  
1. In development/CalendarView.vue, set "config.showModesAsHorizontalMenu: true" in data()
2. $ npm run dev
2. Confirm that the horizontal menu is displayed and functional

2023-06-08 07:13 UTC, tomosterlund requested changes
Thanks for opening this pull request, and for taking the time to contribute. This is much appreciated.

I added some comments. Two of them regarding functional issues, and two regarding maintainability of the library. If any of my comments needs to be clarified, or if you need help implementing them, please let me know :)

2023-06-08 07:13 UTC, tomosterlund commented on src/components/header/Header.vue
Similarly to the hover style, I think we also need an active style for the selected mode, now that all options are displayed in a tab-like manner. Maybe you can play around with the looks of it. My tip would be that `--qalendar-blue` or `--qalendar-blue-transparent` looks OK here.

2023-06-08 07:13 UTC, tomosterlund commented on src/components/header/Header.vue
> +            @click="$emit('change-mode', mode)"
We could also test that this API works when `showModesAsHorizontalMenu: true`

2023-06-08 12:11 UTC, wagnercateb commented
Thank you for your kind and informative feedback, @tomosterlund!

I will do my best to fix this. Apologies for my limited skills...

Best regards, Wagner


________________________________
De: Tom Österlund ***@***.***>
Enviado: quinta-feira, junho 8, 2023 4:13:58 AM
Para: tomosterlund/qalendar ***@***.***>
Cc: wagnercateb ***@***.***>; Author ***@***.***>
Assunto: Re: [tomosterlund/qalendar] feat: add config option to switch modes with horizontal menu (PR #173)


@tomosterlund requested changes on this pull request.

Thanks for opening this pull request, and for taking the time to contribute. This is much appreciated.

I added some comments. Two of them regarding functional issues, and two regarding maintainability of the library. If any of my comments needs to be clarified, or if you need help implementing them, please let me know :)

________________________________

In src/components/header/Header.vue<https://github.com/tomosterlund/qalendar/pull/173#discussion_r1222495748>:

> @@ -274,6 +299,10 @@ export default defineComponent({
       user-select: none;
     }

+    .calendar-header__mode-value:hover {


This style should only be applied when showModesAsHorizontalMenu: true, otherwise we get this result when hovering the closed dropdown
[Bildschirmfoto 2023-06-08 um 08 00 10]<https://user-images.githubusercontent.com/63011648/244279029-9e0115fb-0076-457b-9c91-923d880e5068.png>

________________________________

In src/components/header/Header.vue<https://github.com/tomosterlund/qalendar/pull/173#discussion_r1222548340>:

> @@ -274,6 +299,10 @@ export default defineComponent({
       user-select: none;
     }



Similarly to the hover style, I think we also need an active style for the selected mode, now that all options are displayed in a tab-like manner. Maybe you can play around with the looks of it. My tip would be that --qalendar-blue or --qalendar-blue-transparent looks OK here.

________________________________

In src/components/header/Header.vue<https://github.com/tomosterlund/qalendar/pull/173#discussion_r1222551223>:

>        <div
-        v-if="!onlyDayModeIsEnabled"
+        v-if="showModesAsHorizontalMenu"


Since this behavior is driven by an API exposed by the component, I would prefer this to be tested. You could have a look in Header.test.ts, and maybe add a test case or two that assert that this is only shown when showModesAsHorizontalMenu: true, and otherwise hidden.

________________________________

In src/components/header/Header.vue<https://github.com/tomosterlund/qalendar/pull/173#discussion_r1222553140>:

>          >
-          {{ modeName }}
-        </div>
+          <div
+            class="calendar-header__mode-value"
+            @click="$emit('change-mode', mode)"


We could also test that this API works when showModesAsHorizontalMenu: true

—
Reply to this email directly, view it on GitHub<https://github.com/tomosterlund/qalendar/pull/173#pullrequestreview-1469061766>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ADSWW7D7QDIGXROAWRDO3H3XKF3TNANCNFSM6AAAAAAYZLIHKE>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-06-10 07:51 UTC, tomosterlund commented
@wagnercateb don't worry. It's always a bit of work to get to know a new project. Please don't hesitate to tell me if you need help implementing something. I'm currently working on the last few things for the v3 release, but as soon as that's finished I'll have time to help.

2023-06-16 06:21 UTC, tomosterlund commented
Are you working on the merge conflict already @wagnercateb? If not, I could probably have a look at it over the weekend :) Sorry for the hassle, but the v3 release ended up poking around in almost every single file of the project

2023-06-18 11:08 UTC, wagnercateb commented
Sorry, I have not seen it, I've been pretty busy with a personal project. I'll check it today but if it is a easy fix for you, feel free to look at it.
Good luck with v3!!!

________________________________
De: Tom Österlund ***@***.***>
Enviado: sexta-feira, junho 16, 2023 3:22:08 AM
Para: tomosterlund/qalendar ***@***.***>
Cc: wagnercateb ***@***.***>; Mention ***@***.***>
Assunto: Re: [tomosterlund/qalendar] feat: add config option to switch modes with horizontal menu (PR #173)


Are you working on the merge conflict already @wagnercateb<https://github.com/wagnercateb>? If not, I could probably have a look at it over the weekend :) Sorry for the hassle, but the v3 release ended up poking around in almost every single file of the project

—
Reply to this email directly, view it on GitHub<https://github.com/tomosterlund/qalendar/pull/173#issuecomment-1594168780>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ADSWW7HBS6YLIT7BL7Y6FN3XLP3Q7ANCNFSM6AAAAAAYZLIHKE>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-12-09 21:45 UTC, tomosterlund commented
Closing this due to inactivity. Feel free to open this again if this is still relevant to you, though you might need to cherry pick or even just copy/paste some work from this branch onto a new one, since a lot changed over the past 6 months.

2023-12-09 21:45 UTC, closed without merging